version: '3.9'

services:
  registry:
    image: registry:2
    ports:
      - 5001:5000
    volumes:
      - /mnt/registry:/var/lib/registry
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s